### ISSUE TITLE
Can't disable toggles.

### ISSUE THREAD

**Issue by raulfunkie** [chrisjshull/homebridge-nest#105]
**Describe the bug**
I'm trying to follow instructions to disable the various toggle/switches (Home Occupied, Eco mode, etc). I've defined them on the config.json as "Disable" but they keep appearing. I changed the config.json, tried restarting Homebridge and whatnot.

**To Reproduce**
1. Clone this repo.
2. Change the settings adding username, password and options.

**Expected behavior**
1. Only show Thermostat Device and hide the other "sensors/toggles".

```sh
node 8.16.0
homebridge 0.4.50
```

I'm using the latest version on npm which is 3.0.0

This is my config file for reference (redacted obvious parts):
```
"platforms": [{
		"platform": "Nest",
		"email": "XXX",
		"password": "XXX",
		"options": ["Thermostat.HomeAway.Disable", "Thermostat.Eco.Disable", "Thermostat.Fan.Disable"]
	}]
```

**Comment by adriancable** [comment]
Hi - the issue is that the syntax for disabling the switches has changed between 3.0.0 (on npmjs) and 3.1.0 (on Github). If you follow the docs on npmjs.com it'll describe how you do what you want on 3.0.0. Or, you can wait until tomorrow morning latest for me to publish 3.1.0 on npmjs, and then your config.json will work fine.

**Comment by raulfunkie** [comment]
That makes sense. Thanks so much for your work. I've sent a small donation through PayPal for the hardworking you've put into this the last couple of days/weeks.
