### ISSUE TITLE
HAP Warning: Characteristic ... not in required or optional characteristics for service ... Adding anyway.

### ISSUE THREAD

**Issue by mriksman** [chrisjshull/homebridge-nest#117]
After updating to 3.2.1, I see these for each device in the log;
```
[Nest] initing thermostat "Guest": deviceId: 02AA01AC0615098N structureId: 0de15b80-015c-11e5-9cdc-22000b1e805f
HAP Warning: Characteristic 00000075-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
```
Each thermostat only shows the temperature (unlike before where each had an occupancy switch), and the new global Home/Away switch has appeared.

What are these warnings, and how can we make them go away?

Thanks.

**Comment by adriancable** [comment]
@mriksman - it is caused by a problem with HAP-NodeJS, which is the library Homebridge uses. In the latest homebridge-nest release, I have added a 'Status Active' characteristic to the thermostat to show whether it's online or not - this function works. Unfortunately HAP-NodeJS lists this characteristic as not being supported by the Thermostat accessory, which is not correct. I will file an issue on the HAP-NodeJS Github page, but in the mean time I'll see if there is a workaround to suppress this message.

**Comment by adriancable** [comment]
Workaround added to 3.2.2. Will publish to npmjs later today.

**Comment by Krocko** [comment]
I got also such a warning for the Nest Protect. 
```
HAP Warning: Characteristic 000000BF-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000B7-0000-1000-8000-0026BB765291. Adding anyway.
```

**Comment by adriancable** [comment]
@Krocko - are you sure this is related to Nest and not something else you have set up in Homebridge? Service 000000B7-0000-1000-8000-0026BB765291 is 'Service.Fanv2' - this is some kind of fan but I do not use this service in the plug-in.

**Comment by Krocko** [comment]
Oh sorry. Then it is the Dyson plugin. 
Thanks for clarification.

**Comment by adriancable** [comment]
No problem. The author of the Dyson plug-in should fix it. (or ideally it should be fixed in HAP-NodeJS - I have posted an issue there)
