### ISSUE TITLE
Manually turn off ECO mode

### ISSUE THREAD

**Issue by mrjackyliang** [chrisjshull/homebridge-nest#121]
**Describe the bug**
When I updated the `homebridge-nest` plugin to v3.0.0, the plugin would automatically turn off ECO mode when I ask Siri to turn on the AC. Now, the AC doesn't respond at all, until I turn off ECO mode manually or through Siri.

**To Reproduce**
1. Me: "Hey Siri, turn AC to 75 degrees"
2. Siri: "Ok."
3. Plugin: Does nothing.
4. Me: "Hey Siri, turn off Eco Mode"
5. Siri: "Eco Mode has been switched off."
6. Plugin: AC starts running.

**Expected behavior**
ECO mode is supposed to turn off automatically when AC is on. Started happening on v3.1.1, and now updated to v3.2.2

Include with your bug report this version info:
```
node.js v10.16.0
homebridge v0.4.50
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
```
[7/31/2019, 7:08:59 PM] [Nest] Setting Eco Mode for Hallway to: eco
[7/31/2019, 7:09:14 PM] [Nest] Queuing to set cooling threshold temperature 23.9 °C / 75 °F
[7/31/2019, 7:09:15 PM] [Nest] Cooling threshold temperature set to 23.9 °C / 75 °F null
[7/31/2019, 7:09:43 PM] [Nest] Setting Eco Mode for Hallway to: cool
```

**Comment by adriancable** [comment]
Hi - I've had a look at this behaviour and I think what you are seeing is by design.

In older versions of the plug-in, changing the temperature by Siri while in Eco mode took the thermostat out of Eco mode - I think this is the behaviour is what you were expecting.

But in newer versions of the plug-in, changing the temperature by Siri while in Eco mode adjusts the Eco temperature bands. (Think of Eco mode as like Auto mode, but with different temperature bands). This is the same as setting the Eco Temperatures in the Nest app, so I think it makes sense.

If you have both the upper and lower temperatures set in Eco Temperatures, then you should be able to achieve what you want by saying 'set the temperature range to between X and Y degrees'. This will adjust the Eco Temperature bands, and if the ambient temperature is outside those bands the AC will then kick in.

**Comment by mrjackyliang** [comment]
Ohh, no wonder. I just find it somewhat weird cause I must issue two commands to configure the Nest device. I wondered if there was a tweak to have ECO mode replace auto mode.

It's a weird ask, but would guess it's a nice impliment.

**Comment by adriancable** [comment]
You can achieve what you want, I think, just by not using eco mode at all. Turn it off, and set the temperature bands in Auto mode to what you want.

**Comment by mrjackyliang** [comment]
Yeah, ECO mode is just a selling point for Nest. It really is basically another interface for Auto mode.

In the meantime, I'll find a workaround to set the thermostat as a workaround way for ECO mode.
