### ISSUE TITLE
No more thermostat after migration to google

### ISSUE THREAD

**Issue by Thomas034** [chrisjshull/homebridge-nest#141]
Hi, after migration to google and update app nest on my iphone, on app HOME the thermostat NEST is lost. This is error on homebridge debug.
Have idea for this problem?

Include with your bug report this version info:
```
homebridge-nest --version 3.3.4
node --version 10.16.3
homebridge --version 0.4.50
```
![Annotazione 2019-08-20 102834](https://user-images.githubusercontent.com/54308077/63331071-33b9ac00-c335-11e9-8e8d-03d4c33f117e.png)

**Comment by nscheffer** [comment]
Same for me !

**Comment by nscheffer** [comment]
Do we need to use the previous Nest login/password or the new Google login/password ?
I am confused !
With previous Nest account : 
[21/08/2019 à 17:46:12] [Nest] Initializing Nest platform...
[21/08/2019 à 17:46:12] [Nest] Fetching Nest devices.
[21/08/2019 à 17:46:12] Loading 0 accessories...

With new Google account : 
[21/08/2019 à 17:46:13] [Nest] Auth failed: Nest rejected the account email/password specified in your Homebridge configuration file. Please check
[21/08/2019 à 17:46:13] [Nest] Unable to connect to Nest service.

Thanks in advance.
Regards,

Nicolas

**Comment by Thomas034** [comment]
I think the problem is migration to google.
@nscheffer have installed new version on nest app on your iphone?

**Comment by nscheffer** [comment]
Hi Thomas,

Yes of course the Nest app on the iPhone is updated and works well.
My problem is only with Homebridge

**Comment by adriancable** [comment]
Trust Google to cause trouble!

After migrating to a Google account, your Nest credentials won't work any more - either in the Nest app (using the 'sign in with Nest' option) or in Homebridge.

Right now, the only way to use a Google account with homebridge-nest is via access_token. The easiest way to get it is to go to home.nest.com, then open Dev Tools in your browser and go to the Network tab. Press 'Sign in with Google', and sign in. Then enter 'issue_jwt' (no quotes) in the Filter box, and look at the API response, which will provide the access token in the 'jwt' parameter. I'm working on a better way to get the token for Google Accounts, but right now this is where we are.

Put this into "access_token" in your homebridge config.json, remove "email" and "password", and it should work. Let me know how you get on - this is all very new to me too.

**Comment by nscheffer** [comment]
Adrian,

Thanks for the update.

Nicolas Scheffer 
WhatsApp +33684840663 - nscheffer@me.com

**Comment by stevehoek** [comment]
This is working for me (for now)... how often will the token change?  

Thanks Adrian.

**Comment by adriancable** [comment]
@stevehoek - it should be valid for 1 month.

**Comment by Thomas034** [comment]
Hi adrian, thanks for fast reply. Now work fine with your tips.

**Comment by adriancable** [comment]
It looks like the Google token expires very quickly - about one hour - which is rather a pain. I'm looking to see if/how the Nest app refreshes the token, to see if I can implement the same mechanism.

**Comment by stevehoek** [comment]
FWIW, I routinely keep a tab open in the browser navigated to home.nest.com showing my thermostats, and it is showing the latest sensor data.  When I refresh the tab it does not prompt to login again or anything, even since the Google account migration.  So, somehow its token is still valid 18 hours later.

**Comment by adriancable** [comment]
@stevehoek - what happens behind the scenes is quite complicated. There are actually two tokens in play: one is the Google access token and one is the Nest service access token. There is a simple API call to get a Nest service access token from a Google access token.

The Google access token lasts for 1 hour (and the Nest service access token generated by the API call matches its expiry time). When the Nest web app detects the token has expired (because a Nest call returns a 401 call), some back-end magic happens on the Google side to get a new token. The back-end magic is basically the Google OAuth login flow except that if you are already signed in, it can get a new access token immediately without prompting the user to log in again. Then the Nest web app issues the API call to get a new Nest token and so this "refresh" is seamless. The Nest web app isn't really aware of what's happening behind the scenes - this is handled by the Google client library and it's quite tricky to unpick what it's actually doing. But working on it.

**Comment by mehak-bhatia** [comment]
I connect my Google Nest thermostats and cameras to Amazon Alexa. They have an option for Alexa to access Google nest devices. Would they be using the google oauth login flow as well? Might be worth it to reverse engineer it!

**Comment by adriancable** [comment]
@mehak-bhatia - actually all the reverse engineering required can be done from the Nest web app. Working on it. Will have a workable solution soon.

**Comment by mehak-bhatia** [comment]
Great! Looking forward to it!

**Comment by Thomas034** [comment]
@adriancable great job friend

**Comment by adriancable** [comment]
Just a short update. I've found a way to connect to Google including token refresh. It is a bit of a pain to set up, but the set-up only needs to be done once - unless you log out of your Google account from another device the token refresh will keep the homebridge-nest connection active indefinitely.

Still need to fix a few edge cases but hopefully I will have a new release of the plug-in out on Friday or Saturday.

**Comment by mjgunn99** [comment]
Very cool, thanks for the great work as always Adrian.  And this will work for Google accounts with 2-factor? Any chance this will make things a little more seamless for those of us that run this as a service & use 2 factor?

**Comment by adriancable** [comment]
@mjgunn99 - 3.4.0 now supports Google Accounts! :-)

Not sure about Google with 2FA - please give it a go and let me know how you get on.

**Comment by Barrow-Smith** [comment]
Works with Google account with 2FA! Just configured it using the googleAuth process and I'm up and running. Great job and thank you.

**Comment by adriancable** [comment]
@Barrow-Smith - perfect, appreciate your testing. Have a great weekend. Closing for now.
