### ISSUE TITLE
motion

### ISSUE THREAD

**Issue by ngrimes08** [chrisjshull/homebridge-nest#167]
This plugin used to display motion sensors for the nest hello dorbell camera, had to use in combination with the nest camera plugin, but it worked, and now its gone. was able to set automation to turn on lights if doorbell camera saw motion. any ideas on how to get this back?

**Comment by adriancable** [comment]
@ngrimes08 - the old version of the plug-in which used WWN did display motion sensors for the cameras, but since the rewrite (which uses the native Nest API) this got pulled out. I do have full camera support ready to go, including live video (and also the motion sensors) but this needs Homebridge to update to HAP-NodeJS 0.5.0 to work. As soon as this happens (and I believe it's underway) I'll publish an updated version of the plug-in and you'll be good to go.

**Comment by ngrimes08** [comment]
Awesome! Is there a way to get a notification when it’s ready? And I appreciate your willingness to code this for us guys that don’t know how to code. I just know how to follow instructions lol. Pretty amazing what we can do with computers these days. I was able to update all my plugins last night and Homebridge and node, and was able to not break it all like I normally do when I update them lol.

**Comment by adriancable** [comment]
@ngrimes08 - I'll let you know when it's ready.

**Comment by adriancable** [comment]
In the mean time, if you don't want to wait, you can check out [Starling Home Hub](https://starlinghome.io).
