### ISSUE TITLE
Support for Nest Yale lock

### ISSUE THREAD

**Issue by ojaber** [chrisjshull/homebridge-nest#173]
Would be great to support the Nest x Yale door lock.
https://store.google.com/us/product/nest_x_yale_lock

This device provides current status (locked, unlocked), and can accept commands to lock or unlock the door.
It has modes like "Privacy mode", family/guest permission controls, and lock history/activity.

Once we have Nest Hello and Nest Yale support in homebridge-nest, it complete the nest homekit package for me and I would no longer need the nest app :)

**Comment by adriancable** [comment]
@ojaber - when Homebridge is updated I will release 4.0.0 which (in addition to camera support) implements the Nest protobuf API, which is used exclusively by the Nest x Yale lock. Then it should be relatively easy, in the release after that, to add support for the lock.

**Comment by isaaclimdc** [comment]
@adriancable this is great news! Why does homebridge need to be updated for 4.0.0 to be released? What's the timeframe on that?

**Comment by adriancable** [comment]
The current released version of Homebridge uses HAP-NodeJS 0.4.5 (which is out of date) which does not support bridged cameras, needed for the Nest Cam support to work. Once Homebridge is updated to use HAP-NodeJS 0.5.3, I can then release my plug-in - today it will not work with the standard Homebridge. I don't have a timescale, since I'm not involved with the Homebridge project, but there are several people asking for it to be updated on the Github page so I hope it will happen soon.

**Comment by adriancable** [comment]
Nest x Yale lock is supported in 4.4.0.
