### ISSUE TITLE
Homebridge Verified

### ISSUE THREAD

**Issue by mkormendy** [chrisjshull/homebridge-nest#232]
This plugin should see about getting passed by the homebridge review team:

https://github.com/homebridge/homebridge/wiki/verified-Plugins

Check it out. It's rather simple, and I think this qualifies.

**Comment by donavanbecker** [comment]
@adriancable Any thought on this?

**Comment by adriancable** [comment]
@donavanbecker - apologies for the delay in responding. I have just had a baby, so priorities (or at least free time!) shift a little, for a while.

I had a quick look at Homebridge Verified although conceptually I'm not quite sure what it's for. On one end you have Apple/MFi/HomeKit Certified where Apple approves everything, no source code is available, and users have no flexibility to do their own thing. On the other end you have Homebridge where source code is available, users are responsible for vetting what they use, and have maximum flexibility. Not clear to me that anything in between adds value but I'm happy to be convinced otherwise! Maybe I've just misunderstood something.

**Comment by donavanbecker** [comment]
Nothing to really convince you on, just gives homebridge users The sense of ease that the plugin  doesn’t have any weird scripts running, that it’s a plugin that passes a list of requirements.

Hope all is good with the little one. Sorry if it felt like I was pushing you. Just wasn’t sure what your thoughts were.

Thanks!

**Comment by adriancable** [comment]
@donavanbecker - got it - did some more research and I like it. Apologies for sounding dismissive earlier on - that wasn't my intention!

**Comment by donavanbecker** [comment]
Your good. never felt like you were. Thanks.

**Comment by donavanbecker** [comment]
You should join the discord server :)

**Comment by mkormendy** [comment]
@adriancable congrats on the new baby! Boy or girl? Have they already started coding? 😉

I'm in the process of getting my plugin verified, and one of the things I like is that it forces me to think more about the user experience, from ease of configuration with the config-ui to graceful error handling and just a good overall sanity check on my code.

Your plugin is quite amazing already so I think it would be trivial to add it. But that's your call entirely.

**Comment by mkormendy** [comment]
I see it now. Thanks guys!
