### ISSUE TITLE
HomeAway.Disable.device_id setting ignored

### ISSUE THREAD

**Issue by pindey** [chrisjshull/homebridge-nest#233]
HomeAway.Disable works fine, when scoped to a specific device, the option is ignored and the device's Home/Away switch appears in homekit

**Comment by adriancable** [comment]
Hi @pindey - I'm not exactly sure what you mean by the question. The Home/Away switch is not a property of a device, it's a property of the structure, so not clear to me what you mean by "scoped to a specific device".

Do you mean structure_id instead of device_id, and are you saying that HomeAway.Disable.structure_id doesn't work for you?

**Comment by pindey** [comment]
That makes much more sense! :) using HomeAway.Disable.structure_id worked perfectly
