### ISSUE TITLE
After server reboot Nest is reset and removed from automations

### ISSUE THREAD

**Issue by jpetticrew** [chrisjshull/homebridge-nest#263]
**Describe the bug**
Whenever my iMac restarts, my Nest is reset in the home app and it is removed from my automations. 
**To Reproduce**
1. Restart iMac (Homebridge server)
2. In Home app, Nest is reset back to “show as single tile”, they are all in “default room”, and all four switches are shown in favorites. 

**Expected behavior**

Include with your bug report this version info:
```sh
node --version 14.0.0
homebridge --version 1.1.0
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by Seaniau** [comment]
Unsure if this will directly help you or Devs but, chiming in anyway;
I find this happens when the Homebridge instance is started and it cannot initially connect to Nest. Not something I experience when restarting my Homebridge instance, unless the Nest authentication key/cookie has expired.

**Comment by kbrashears5** [comment]
this just happened to me too, I have all the latest versions. storm caused a power outage and when my raspberry pi turned back on all my nest stuff was gone. mine actually got removed from homekit, not reset back to default room.

I tried removing the bridge and adding it back, it adds it but says "Additional setup required, go to manufacuturer app blah blah blah".

Looking at logs it's saying my auth expired:
Jun 10 20:15:55 raspberrypi homebridge[1526]: [6/10/2020, 8:15:55 PM] [Nest] Google authentication was unsuccessful. Make sure you did not log out of your Google account after getting your googleAuth parameters.
Jun 10 20:15:55 raspberrypi homebridge[1526]: [6/10/2020, 8:15:55 PM] [Nest] Access token acquisition via googleAuth failed (code undefined).
Jun 10 20:15:55 raspberrypi homebridge[1526]: [6/10/2020, 8:15:55 PM] [Nest] Unable to authenticate with Google/Nest.

Following the Google auth steps https://www.npmjs.com/package/homebridge-nest was able to get it back in home app

**Comment by rnilssoncx** [comment]
I just had the same experience.  The google auth failed and after I fixed and rebooted all the devices are "new" in homekit, which breaks everything.

Could the devices be saved so that in the event of a login failure they can still be provided to homekit?

**Comment by Seaniau** [comment]
It only happens when you start the Homebridge instance and the Auth fails. If your Homebridge instance is already running while the Auth expires, it does not remove the devices. Then, in my experience, as long as you stop the Homebridge instance, edit the config file with new Auth details and then start the Homebridge instance again, your device stay the same.

If your devices are not responding; Don’t reboot your Homebridge. Check the log, if you see Auth failed; stop it, renew details, start it.

**Comment by jpetticrew** [comment]
It’s not just if auth has expired. The last two times this has happened to me, Google auth has not been expired.

**Comment by adriancable** [comment]
So to be honest I'm not sure what the right thing to do here is. @Seaniau & @rnilssoncx - you've nailed the cause. The problem is, if the plug-in starts and the auth fails, what is it supposed to do? There are only three options, (1) abort Homebridge entirely, (2) return an empty accessory array to Homebridge, (3) cache how things were on the last start, and return the same accessory array.

(1) is what the plug-in used to do. Upside: it won't remove your accessories or automations if the auth failed. Downside: lots and lots of people complained that their other plug-ins stopped working if something was wrong with Nest.

(2) is what the plug-in does now. Upside: doesn't interfere with other plug-ins. Downside: kills room assignments, favorites and automations when it happens.

(3) is possible, but not clear how we make a reasonable UX. Upside: doesn't interfere with other plug-ins, and doesn't kill Nest associations if there is an auth issue. Main downside is: when it happens, it isn't obvious to the user that it's happened since the accessories are all still there and don't show 'No Response', they just stop working. At least with options (1) and (2) you immediately know this has happened when Homebridge starts, and can fix it. There used to be Characteristic.Reachability that we could set to false, which would make the accessories appear with an exclamation mark, which is great. Unfortunately this was deprecated in iOS 10 I think and no longer works.

If there was a way to do #3 but indicate to the HomeKit user that the accessories are non-functional, then it probably becomes a good approach but not sure how to do it. Any suggestions?

**Comment by jpetticrew** [comment]
Number 1 because it doesn’t cause any loss of config and its fail state is less disruptive. 

—
Jeremy Petticrew
713.591.9197

**Comment by adriancable** [comment]
@jpetticrew - that was also my vote, but the user masses disagreed.

My current thought is to add a switch in the configuration to let the user choose between #1 and #2.

**Comment by jpetticrew** [comment]
I would definitely appreciate a switch, but I also understand that stuff like that isn’t as easy as it seems, and also that you’re doing this for free. I appreciate you and I am happy to know that it isn’t necessarily a bug. Just a by-product of trying to make the most people the most happy. 

—
Jeremy Petticrew

**Comment by QandnotU** [comment]
Are you less likely to have these auth issues using the startling hub? I’ve been losing my accessories far too often lately on macOS. You inherently are more prone to losing auth running HomeBridge on a desktop. Re authenticating and adding accessories back is certainly laborious.

**Comment by jelockwood** [comment]
HomeBridge-Nest supports two auth methods, the old Nest account method and the newer Google account method.

Does this problem apply equally to both methods or is one 'better' than the other? If it happens more on the old Nest method then upgrading to a Google account may at least help. If it happens more on the Google account method then there is nothing you can do since you cannot downgrade to a Nest account.

**Comment by adriancable** [comment]
@jelockwood - it's a good question. The problem will happen whenever homebridge starts and, for some reason, the plug-in cannot authenticate with Nest, and so returns an empty device list to homebridge. The question is - under what circumstances can this happen with Google, and with Nest?

With Google, sometimes this 'just happens'. We don't know why. Some people use the same cookies for months and months without issues. Others, the cookies seem to 'expire' after 2 weeks. With Nest accounts, the access tokens are in principle valid forever, or at least a very long time - at least, we're not aware of them expiring, but we also don't know that they last indefinitely for sure.

I would say that, from what we know, the Nest access token method seems less likely to expire than the Google cookie method. So, at least just on that consideration, keep your Nest account if you can.

**Comment by nielsvaneck** [comment]
> If there was a way to do #3 but indicate to the HomeKit user that the accessories are non-functional, then it probably becomes a good approach but not sure how to do it. Any suggestions?

Could you register a fake sensor or other device that would indicate authentication status?  In case the cookie expires, that sensor could either change its state to indicate auth failure or show up in the status overview as "not responding"..   

I have 2 thermostats, each with 2 additional sensor units, 3 protects and 6 locks..  so the "Default Room" experience is far from optimal.

**Comment by adriancable** [comment]
Consolidated under #299.
