### ISSUE TITLE
Unable to remove Nest Protects from favourites

### ISSUE THREAD

**Issue by MED1975** [chrisjshull/homebridge-nest#279]
Hi.

I recently noticed that my Nest Protects had reappeared in favourite accessories in the Home app. I am able to move them to different rooms but unable to change the setting for include in favourites.

I have completely uninstalled your plugin and added back but this has not helped. I am able to add and remove my thermostat from favourites without issue.

Homebridge is running in docker. 1.1.1 your plugin is 4.4.6

Thanks

**Comment by mbierman** [comment]
The Plugin has no control over this.

**Comment by adriancable** [comment]
@MED1975 - yes, we've seen this too, not just with homebridge-nest or even with homebridge but with all HomeKit devices. It's almost certainly a bug on the HomeKit side since as @mbierman correctly comments the 'favorites' status and even room assignments are managed by iOS and the devices themselves don't have any access to it.

Things that people have done which help: sign out of iCloud on your iOS device, go back to Home app (note devices have gone), sign back into iCloud, return to Home app, and wait a few moments for the HomeKit devices to resync.

Alternatively you can remove the bridge from the Home app (Home tab, press 'Edit' on the top, press '>', scroll down to Hubs & Bridges, select Homebridge, then Remove), and then re-add it.
