### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by rsachoc** [chrisjshull/homebridge-nest#288]
Trying to get my Nest Thermostat working via HOOBS - HOOBS is docker image. Plugin v 4.4.6

Enter all details per required documentation, then save, which forces a restart. Get the following:

````
Bridge is running on port 51826.


Got SIGINT, shutting down Bridge...


Loaded plugin "homebridge-nest".


[Nest] Fetching Nest devices.


[Nest] Access token acquisition via googleAuth failed (code ERR_INVALID_CHAR).


[Nest] Unable to authenticate with Google/Nest.


Bridge is running on port 51826.
````

**Comment by adriancable** [comment]
@rsachoc - this means that there is an invalid (i.e. non ASCII) character in issueToken, or cookies, in your config.json. Usually it's caused because something got messed up when you copied and pasted the issueToken URL from your browser. (for example, you pasted it into a word processor, then pasted that into the config.json file, and the word processor replaced an ASCII quote character with a Unicode equivalent, or similar)

If you make sure issueToken and cookies are pasted verbatim everything will work.

**Comment by rsachoc** [comment]
Thanks for that. Finally working, I tried copy pasting into notepad first, then into the web interface, didn't work. Ended up shutting down the docker container, then editing the "config.json" file in/etc directly and pasting in from Firefox into nano and worked! Thank you.

**Comment by danesparza** [comment]
I'm also getting this issue.  I also tried copy/pasting directly from firefox into nano on the Raspberry pi.  No dice.  Same error.

**Comment by adriancable** [comment]
@danesparza - in our instructions we ask people to use Chrome, not because we want to be mean to Firefox users but because other browsers do things like abbreviate headers with ... symbols and the like which will cause this issue.

Please can you try following the instructions exactly as written, and if you still have an issue then let me know and I'll do my best to help.
