### ISSUE TITLE
[Nest] Access token acquisition via googleAuth failed (code 400)

### ISSUE THREAD

**Issue by DDanDesmond** [chrisjshull/homebridge-nest#293]
Had this working perfect with my home bridge however having an [Nest] Access token acquisition via googleAuth failed (code 400) Issue
I redid the API COOKIES etc guide and still getting the same error:
Wondering has google blocked this?

**Comment by leroyrichjr** [comment]
Same issue here

**Comment by adriancable** [comment]
@DDanDesmond / @leroyrichjr - before we try to troubleshoot, a note. The plug-in has tens of thousands of users, and if Google had broken something, there would likely be a firestorm and not just two people with issues. And - note that Google has broken things in the past - and when that happened there was indeed a firestorm. So my suspicion is that this has not happened. Plus, I tried following the instructions again just now and everything still works.

So first please try following the instructions again, carefully, because it is easy to mess up. If you still have issues, please send me your config.json to adrian.cable@gmail.com and I will take a look.

**Comment by efipso** [comment]
What I found a few weeks ago on my last reconfiguration is that the credentials obtained using Firefox are invalid. I had to install Chrome and, with credentials obtained using it, works like a charm.

@DDanDesmond @leroyrichjr 
I don't remember the error code given, but maybe your problem is something like this?

**Comment by mbierman** [comment]
@efipso the credentials should be the same regardless of the browser. Perhaps Firefox changes the formatting of the response in some way? Did you try comparing the text strings from Chrome and Firefox?

**Comment by efipso** [comment]
@mbierman yeah, I know, but the credentials obtained from Firefox don't worked.
If I remember well, 'cookies' and 'apiKey' are the same on both but the issueToken are a bit different. I don't know why.
When I have to reconfigure the plugin and if it happen again I'll try to get more info

**Comment by DDanDesmond** [comment]
FYI forgot to update this. Adrian helped me with this and it was user error (me) but all sorted now. Thanks again
