### ISSUE TITLE
Support Google Nest Device Access program

### ISSUE THREAD

**Issue by colejd** [chrisjshull/homebridge-nest#305]
**Is your feature request related to a problem? Please describe.**
Now that Google's Nest Device Access program is available, homebridge-nest should be able to access what it needs right through that API.

**Describe the solution you'd like**
Support the Nest Device Access program.

**Additional context**
https://developers.googleblog.com/2020/09/google-nest-device-access-console.html

**Comment by adriancable** [comment]
@colejd - if only! I think this is highly unlikely to ever be possible/practical.

Google has two different memberships for the program, a developer membership and a commercial membership. The developer membership limits the total number of users to 100, amongst other restrictions. The commercial membership includes things like a mandatory annual third party security assessment which is expected to cost around $15K. Clearly neither of these work for a free plug-in with lots of users. Google seems to have totally forgotten the open source community exists here, which is very disappointing.

Other reasons why Device Access underwhelms: it doesn't support the Nest x Yale Lock or Nest Secure, and I understand never will because Google only trusts itself, and no third party developers at all, to control home security operations. And, the program will also never support legacy Nest accounts.

**Comment by tijunoi** [comment]
@adriancable
Would it not be possible to provide the OAuth client id and credentials as config to the plugin, and every user have their own developer account setup?

Regarding the not available devices, have both access options available? Both would have to be maintained. 

Maybe it would make more sense to have another plugin that does Device Access?

**Comment by themainframe** [comment]
I think it could be made to work but each user would need to sign up for an Individual Device Access account (and pay the non-refundable 5 USD sign-up fee, thanks Google). You also need a GCP Project (see https://developers.google.com/nest/device-access/get-started) since access is provided to SDM via GCP. I just went through the process and it's not fun.

The mind boggles, truly. Why can't I just log in to my Nest/Google account and generate/revoke API keys that provide access to a simple REST API (even if it is heavily rate limited for non-commercial users)? We've really gone backwards.

**Comment by farcaller** [comment]
Scraping the auth tokens from chrome devtools is even less fun, though!

**Comment by themainframe** [comment]
I don't think this is any better, @farcaller, honestly. If anything, this is slightly worse since it requires:

1. Payment ($5, but still, requires a credit card, and a payment is a payment)
2. Non-out-of-box tools. Use of `curl` to make arbitrary POST requests is one of the setup steps. Postman could be used instead I suppose. Will all users have that? Especially users who don't "do" CLI and will use `homebridge-nest` via `config-ui-x` or whatever? The current approach, though janky, is possible with just a browser.

**Comment by farcaller** [comment]
The current approach regularly loses the auth cookies for me and requires reauth; this one will be (supposedly) less fragile, being the actual official way to use the API.

**Comment by adriancable** [comment]
Maybe someone wants to fork homebridge-nest and retool it using the Device Access API.

Completely rewriting the API layer is a huge amount of work ... and right now the reward for that huge amount of work would be removing support for Nest Protect and Nest x Yale Lock, removing support for Nest accounts, and forcing everyone to pay $5 to Google to use a "free" plug-in ... just doesn't work for me on any level. Sorry.

**Comment by themainframe** [comment]
I do think the current approach needs improvement. I've seen other Nest plugins that include a setup script that invokes Chromium/phantomjs (that sort of thing) to do the setup. I do agree that the Device Access API isn't the right tool though. Not entirely sure who Google thought that would be useful for.

**Comment by adriancable** [comment]
@themainframe - I have experimented with using Selenium/Puppeteer to automate the Google cookie collection (which is what the homebridge-nest-cam plug-in does). The issue is that Google puts quite a lot of effort into breaking automated logins (producng a 'this app or browser is not secure' error and blocking the login), and they regularly improve this, so it becomes a little bit of a cat and mouse. That's not to say this approach doesn't have any value. (For the avoidance of doubt, a note to the author of homebridge-nest-cam - you have made a great plug-in!)

I do recognize the current approach with expiring cookies isn't great. There are some things you can do which are not zero friction but can be quite effective. For example, create a dedicated Google account just for Nest devices which is not used for anything else. This seems to reduce the frequency of unexpected log-outs. I have a test Google account with cookies that are still functional that were obtained 6 months ago.

**Comment by themainframe** [comment]
Appreciate the effort Adrian. It's tough but I'm pretty convinced the current approach (though not ideal) is still better than the new API. Might try that separate Google account idea. I assume you just added that account to your Nest Home or whatever?

**Comment by adriancable** [comment]
@themainframe - a few months back, I created a new Google Account in the Nest app, removed one of my Nest devices from my old account and re-added to the new account in the Nest app. It's remained logged in ever since.
