### ISSUE TITLE
Weird issue setting Home/Away

### ISSUE THREAD

**Issue by hansenc0705** [chrisjshull/homebridge-nest#33]
So I don't think this is an issue directly within homebridge-nest but maybe someone can assist in troubleshooting? After a couple days using the homebridge-nest my nest will start going into away mode on its own. I can set Home back in the nest app or within the Home iOS app and a few mins later the house will go back into away mode.

I'm watching the logs in homebridge and its not logging that HomeKit is doing this yet when I unauthorize the homebridge-nest integration this issue stops.

Now as I write this it just happened so I go into the Home iOS app to change back to home and I'm seeing a blocked message in the homebridge logs.

`[2018-4-7 07:46:37] [Nest] Setting Home for 09 - Living Room Thermostat (Downstairs) to: home
[2018-4-7 07:46:37] [Nest] Setting Home for 10 - Loft Thermostat (Upstairs) to: home
FIREBASE WARNING: set at /structures/xxxxx-nlDDJe0sCd2YekJUOvNHqVMFug/away failed: blocked
FIREBASE WARNING: set at /structures/xxxxx-nlDDJe0sCd2YekJUOvNHqVMFug/away failed: blocked`

**Comment by chrisjshull** [comment]
Odd, you are likely being blocked because of the rate-limiter on the nest API.
Can you share a full set of logs? And be sure to call out what time the nest seeing to change it's settings on its own?

can you:
1. shut down homebridge
1. launch homebridge in debug mode: `DEBUG=* homebridge -D`
1. attach the log once homebridge is up and running.

**Comment by adriancable** [comment]
Out of date. Should be resolved now.
