### ISSUE TITLE
Nest thermostat temperature can no longer be changed or set in a shortcut. Works fine in home.

### ISSUE THREAD

**Issue by WIMWG** [chrisjshull/homebridge-nest#330]
**Describe the bug**
Can not change the temperature setting of the thermostat used in a shortcut
In the home app i can set the temperature of the thermostat

**To Reproduce**
1. Try to change the temperature of the thermostat used in a shortcut
2. Shortcut app locks ... and finally quits

**Expected behavior**
Temperature setting is changed

** Versions
latest version of hoobs and nest plugin
iphone with ios 14.1 and ipad with ipados 14.1

no entry in hoobs logging

**Comment by nitronl** [comment]
If the Home app controls the Nest thermostat correctly via Homebridge and the Nest plugin, then doesn't it seem likely that your issue is with Shortcuts not Homebridge-nest?

**Comment by WIMWG** [comment]
Hi Chris

I think you are the best person to answer that question.

I do not know to which extent the Shortcuts app uses Homebridge-nest. In shortcuts I change the temperature, but it is not actually changed, but does Shortcuts uses Homebridge-nest then ?? 

Also I do not know if it was since i upgraded to ios 14.1 or homebridge-nest 4.4.15
After the release of both those versions i did not try to change the temperature setting in Shortcuts.

Can  you reproduce this issue ?

I did google first and I did google apple support but could not find anything.

Regards
Wim

**Comment by adriancable** [comment]
@WIMWG - the Shortcuts app does not 'use' homebridge-nest in any meaningful sense, or vice versa. We have no awareness of Siri, shortcuts, automations, rooms or anything else. We simply publish a device using the HomeKit API, and everything else happens on the iOS/iCloud side and we have no visibility or control over it. So unfortunately I'm not sure there's a great deal we can do.

What happens when you run the Shortcut? Do you get an error, or does simply nothing happen?

**Comment by WIMWG** [comment]
Hi

What happens is that i can change the temperature, i can increase or decrease it.
But when you close the ‘accessory’ in order to save the setting, the screen freezes.
But you dont have to change the setting, just opening the accessory and then closing it, freezes the screen, the app.

This does not happen when i open the nest accessory switch : home on/of
I can change that setting and save it, no problem

Nothing is logging in hoobs logging

Groeten
Wim

**Comment by WIMWG** [comment]
after reading your mail a second time.
I can run the shortcut no problem, but with the old temperature setting.

I can not make a new shortcut with the temperature accessory. The old still works.

Shortcuts gets the accessory from the home app

Groeten
Wim

**Comment by adriancable** [comment]
@WIMWG - you will not see anything in the HOOBS log because, as I said previously, HOOBS, Homebridge, homebridge-nest, etc. have zero awareness or interaction with shortcuts, Siri, etc. HOOBS, Homebridge, homebridge-nest have no idea at all when you are creating a shortcut, leaving a screen on your iPhone, entering a screen on your iPhone, etc. and so if your shortcuts app is crashing at that point, the cause lies elsewhere.

My only suggestion is that you delete your HOOBS bridge from HomeKit, reset HOOBS, and then re-add, to see if that fixes it. And/or sign out of iCloud, go back to Home app (note all devices gone), sign back into iCloud, go back to Home app (note all devices are back). Maybe the HomeKit database has become corrupted somehow and either of these may fix it.

**Comment by WIMWG** [comment]
Hi Adrian

I only suggested that when changing the setting , apple home sends a request that is not answered anymore. I never suggested that homebridge had any awareness of what happens in the apple ecosystem.

Groeten
Wim

**Comment by adriancable** [comment]
@WIMWG - sorry, I don't think I was really clear before. Let me try to explain the point a little better. Of course, we're responsible for answering HomeKit API requests. But, there is no difference on our side (and in fact we have no way of knowing) whether that request comes from a Shortcut, or from Siri, or from changing a control in the Home app.

What this means in practice is that, if you are able to change a control in the Home app, but not change the same control using a Shortcut, or using Siri, the problem is somewhere on the Apple side of the fence. Hence the suggestion to try removing/readding HOOBS from HomeKit, and/or logging out and then back into iCloud, which refreshes the HomeKit database.

Good luck figuring it out!

**Comment by WIMWG** [comment]
Hi 

I have contacted apple support. (chat)
They will call me back tomorrow.

Thanks for your time

Groeten
Wim
