### ISSUE TITLE
High data usage over cellular

### ISSUE THREAD

**Issue by gman-wa** [chrisjshull/homebridge-nest#334]
Running 4.4.15, and also saw this behavior about a month ago with the current version at that time.

Two Protects, One Gen 2 Thermostat.

Googe auth.

Raspberry Pi

npm 6.14.8

Homebridge Beta - 1.3.0-beta.24

With this plugin enabled (disabled one plugin at a time to isolate this one) the entire family is seeing very high data usage over cellular, battery drain, etc.

Anyone else seeing this issue?

**Comment by adriancable** [comment]
When you say cellular, do you mean that you're seeing high cellular data usage on your iOS devices, when the plug-in is active? If that's the case, it's very hard to see how homebridge-nest (or anything else Homebridge-related) could be the cause. Homebridge I presume is running on your Raspberry Pi, but presumably that's not using cellular data, or is it? If you can clarify that would be helpful.

If you're seeing your iPhone use a lot of cellular data then it's hard to see how any software running on another device on your LAN could be the cause. If you go into Settings / Mobile Data on your iPhone, it will show you what apps are using the data. What does that say?

**Comment by gman-wa** [comment]
ok, true, then i'll amend this to be 'high data usage' in general, which becomes more apparent on cellular as it noticeably eats into the data plan allowance.  at home over wifi i don't really care.  and on the iphone, it doesn't break down homekit data usage over wifi the same way it does over cellular.

**Comment by adriancable** [comment]
@gman-wa - the problem is that I just can't see how this could be possible. How can it be true that software on a Raspberry Pi, connected to your LAN, could causes high data usage on a different device (your iPhone) on a different network (cellular)?

I suspect that something else was causing your high data usage, and the fact that it dropped when you disabled homebridge-nest was a coincidence. If you have the time to do a controlled experiment, where for the next say 10 days you flip a coin to decide whether homebridge-nest is on, or off, for that day, then record the data usage that your iPhone reports, then post the screenshots for each day, that would be approaching statistical significance.
