### ISSUE TITLE
Elapsed time since occupancy sensor triggered

### ISSUE THREAD

**Issue by fleiscpj** [chrisjshull/homebridge-nest#343]
**Is your feature request related to a problem? Please describe.**
Cannot control the duration of time after motion is not detected to trigger an action. 

**Describe the solution you'd like**
Another field/characteristic that provides elapsed time since motion was detected from my nest smoke alarm. This would allow an automation in Home Controller to use that characteristic. 

**Describe alternatives you've considered**
Less desirable would be a configuration parameter to set the period of time before the occupiency switch switches from on to off. 

**Additional context**

**Comment by adriancable** [comment]
@fleiscpj - can you tell us exactly what you're trying to achieve? From the information provided, I don't think any new characteristic would be required or useful, but without knowing what you're trying to accomplish, very hard to advise. Thank you!

**Comment by fleiscpj** [comment]
I think ultimately if I could change the threshold of when the motion sensor reports no motion detected that would be ideal. In other words, after no motion is detected the motion detected would switch to no after a configured interval. This allows me to have lights turn off less frequently. It is pretty annoying to be sitting on the couch and the lights shut off because it did not detect motion of whatever small interval it is Nest default.

**Comment by jshdesigns** [comment]
+1 for this request. Right now the Occupancy/Motion sensor appears to timeout after 10mins from sensing motion. It would be nice to have the ability to adjust the threshold of the timeout to be quicker for automations in case multiple motion triggers happen within that 10mins. This would closer match the Pathlight feature of the Nest Protect.
For example, an automation that turns on a light when occupancy/motion is detected. The automation turns off the light after 1 minute from being triggered. The automation wouldn't run again for 10mins because the occupancy/motion is still triggered during that time, leaving it dark for at least 9mins even if someone walked passed it again.

**Comment by DigitalElise** [comment]
+1 from me too, I agree with everything @jshdesigns says, right now the sensor isn't very useful in HomeKit as the timeout is so long.

**Comment by adriancable** [comment]
Unfortunately, Nest decided that 10 minutes is the right number and we don't have any influence over it. It's because the function internally is used as an occupancy sensor, not a motion sensor: for occupancy sensors it makes sense for motion to indicate occupancy immediately, but to have a rather long reset time (because just because you stop moving for a few moments, doesn't mean you've left the room).

So for example there's no way for us to detect multiple motion events after the first within the 10-minute window. After triggering, the sensor goes "blind" for 10 minutes. Sorry!

**Comment by jshdesigns** [comment]
That is unfortunate, but also wonder if that is still the case in their API? I ask because the Pathlight feature works like a motion sensor. The light on the Protect will turn on and stay one while it detects motion and timeout after 5secs when it stops seeing motion. It will immediately turn back on when it sees motion again.

**Comment by adriancable** [comment]
@jshdesigns - internally, the Nest Protect does have a motion sensor with a fast response time. This sensor is used directly by the Pathlight function, but it is not exposed to the Nest API. In other words, the Nest Protect does not report the motion sensor state to the Nest cloud service at regular intervals. Therefore, we cannot read it directly.

What Nest Protect **does** report to the Nest cloud service is a presence state. This is basically a filtered version of the motion sensor, which triggers immediately but then has a 10-minute relaxation time. This presence state is used by the Nest service to determine the Home/Away status for the structure, in conjunction with the presence state reported by other Nest devices.

Because we don't have access to the signals inside the device, only what the device reports on the network, we're limited to what the device reports on the network. For the wired Nest Protect, this is unfortunately just the presence state, which has the 10-minute limitation. (The battery Nest Protect does not even report this over the network.)
