### ISSUE TITLE
Random ECONNRESET messages

### ISSUE THREAD

**Issue by StephenShamakian** [chrisjshull/homebridge-nest#345]
The plugin seems to be working ok but I randomly get ECONNRESET errors in my homebidge log from this plugin:

[12/24/2020, 8:36:56 AM] [Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[12/24/2020, 8:36:56 AM] [Nest] Retrying in 10 seconds.

**Comment by maconic** [comment]
Same Problem here: 

[Nest] Nest API call to subscribe to device settings updates returned an error: ECONNRESET

For me the plugins stops working after this. I have to add that it worked after installation and it also works if I start with homebridge -D just not when I start homebridge as a service :(

**Comment by benruset** [comment]
I'm seeing the same behavior as maconic. I have had the plugin installed for a long time and it's been working perfectly so I'm not sure what might have changed to break it.

**Comment by maconic** [comment]
Actually for me it was a real connection issue and went away.

**Comment by StephenShamakian** [comment]
I'm still having this issue...

![image](https://user-images.githubusercontent.com/6382844/104607359-c061ba00-564e-11eb-851a-5f2abbf79509.png)

**Comment by StephenShamakian** [comment]
@adriancable any insight into this issue? Still getting spammed with connection reset errors in logs when the Nest plugin tries to communicate with the "device settings updates" endpoint.

Thanks!

**Comment by adriancable** [comment]
Sorry, @StephenShamakian, as I think has been commented by me and others previously, ECONNRESET is a low level network issue. It means the connection is dropped somewhere between Nest's server and your server. It is not a software issue, and isn't something that's related to homebridge-nest, or homebridge at all for that matter, and therefore not something I can "fix".

Occasional network drops are not unusual. The plug-in should simply reconnect to the Nest service when this happens, and it should not generally affect your use of the plug-in.

**Comment by StephenShamakian** [comment]
@adriancable these are not occasional by any means...
![image](https://user-images.githubusercontent.com/6382844/106295831-ec6c6600-621e-11eb-909f-00b0dd4cf00f.png)

I'm aware what a connection reset error is. I'm just wondering if Google changed something and your code is referencing an old API endpoint? As I seem to not be the only one having the issue. Maybe if I knew the API URL I could do some digging on my side with Postman. Or maybe the connection to the endpoint just needs a higher timeout due to a slow response from Google's servers? That would be a code change on your side :)

Thanks!

**Comment by adriancable** [comment]
Hi @StephenShamakian - take a look at lib/nest-endpoints.js. All the endpoints the plug-in uses are defined in that file - hope this is helpful.

ECONNRESET isn't a timeout (that is ECONNABORTED). It means that a connection has been established, and then the connection was closed unexpectedly - not by the client. So, it could be due to something on the remote end, or with some intermediate relay. 

The one code change that may be worth making is to reduce the retry delay from 10 seconds to 1 second after ECONNRESET, since it is probably safe to make another call immediately after this error occurs (although I may need to be careful about rate limits). The frequency that this is happening to you - on average, once every few minutes - shouldn't impact the performance of the plug-in materially.

**Comment by StephenShamakian** [comment]
@adriancable I mean if it is irrelevant to the performance of the plugin, maybe in addition only output these type of errors in DEBUG mode? That way it doesn't complete spam the logs from meaningful messages from other plugins?

I did take a look at the endpoints JS when I first posted this issue and it looks like it just uses the standard home.nest.com endpoint which makes no sense, as I have no issues with that endpoint when I use it via the web UI. But granted a web UI is very different than what this is.

**Comment by adriancable** [comment]
Hi @StephenShamakian - what exactly do you mean when you say you have no issues with the web UI? I would not expect occasional ECONNRESET errors to cause any issues at all, either with the web UI or with the plug-in. What makes you sure these errors are not happening at the same frequency with the web app? How would you know?

**Comment by StephenShamakian** [comment]
@adriancable I am not sure, which is why I said a WEB UI is not exactly the same as a HomeBidge plugin. As just becasue I'm not getting connection resets in the browser; backend calls *could* still be getting connection resets. And without keeping the browsers dev tools open all the time I would never know.

But my point is they are handled better. Is there a way to hide these messages in my logs if they don't affect the functionality of the plugin? That to me means these should only be debug messages as functionality of the plugin is not affected.

**Comment by adriancable** [comment]
@StephenShamakian - I think I'm still not 100% clear what the issue we're trying to address here is. The homebridge log output is intended for developers, principally to troubleshoot if things aren't working right. And in this case, any network level error can be useful information, even if those errors individually don't affect the functionality.

Take almost any web app ... like home.nest.com, and open the browser console. You will almost certainly see a LOT of "error messages" there, even when everything is working fine. I've attached an example from home.nest.com just now. You may think it looks pretty scary, being full of 'violations' and ERR_HTTP_RESPONSE_CODE_FAILURE and many other things. But the key thing to remember is none of this information is intended for your eyes, or mine. It's intended for the eyes of Nest devs only, and they would see these "errors" and say everything is normal.

<img width="1680" alt="Screenshot 2021-01-29 at 11 24 43 AM" src="https://user-images.githubusercontent.com/6544927/106318841-5a1b9080-6225-11eb-9cb7-43b7d9f46482.png">

**Comment by StephenShamakian** [comment]
@adriancable HTTP errors are not the same as connection reset errors. I just seriously doubt your complacency into why you seem to think a connection reset at this frequency is normal operation. My point is if its normal, then its not helpful as it hampers/masks debugging capabilities of other more serious problems with other plugins due to the high amount of false positives this plugin is generating for "normal" operations. 

I'm not saying they should be removed. And if you think this error is normal then why not add a condition around this line: https://github.com/chrisjshull/homebridge-nest/blob/master/lib/nest-connection.js#L1140 to only output if the HomeBridge debug flag is set to true?

**Comment by StephenShamakian** [comment]
@adriancable I mean how is this useful to anyone if this is normal operation...
![image](https://user-images.githubusercontent.com/6382844/106320447-e7201300-6240-11eb-9dd0-f196a6db1090.png)

**Comment by StephenShamakian** [comment]
@adriancable One thing I am noticing from home.nest.com via browser dev tools is super long wait times for the subscribe endpoint. Which again kind of leads me to believe it's some sort of timeout issue:

![image](https://user-images.githubusercontent.com/6382844/106321649-95788800-6242-11eb-9d29-b07ed382263e.png)

**Comment by adriancable** [comment]
@StephenShamakian - the 'subscribe' call is a long poll. The call will not return until there is a device property change in at least one of your devices. If this doesn't happen within 2 minutes, the call expires and we issue another one. We basically duplicate the behaviour of the Nest app in this regard.

Again, the Homebridge log is intended for the eyes of the developer plug-in, if there are issues, and its contents are frequently useful - to the developer plug-in. The Homebridge log is not intended to be useful to you.

I fully understand, appreciate and respect your opinion that you would rather not see network errors in the log, if they don't impede normal operation. But, I respectfully disagree, and since the sole purpose of the log is to be useful to plug-in developers and not end users of Homebridge, ultimately what goes into the log is the sole decision of the developer - which is me in this case.
