### ISSUE TITLE
Plugin generated a warning from the characteristic 'Heating Threshold Temperature'

### ISSUE THREAD

**Issue by leendersf** [chrisjshull/homebridge-nest#376]
**Describe the bug**
I get this error in the logs:
[homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 10. See https://git.io/JtMGR for more info.
**To Reproduce**
1. Run Homebridge

**Expected behavior**

Include with your bug report this version info:
```sh
node --version v14.15.5
homebridge --version
Npm version 6.14.11
/homebridge # homebridge -V
Initializing HAP-NodeJS v0.9.2...
1.3.1
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by adriancable** [comment]
This appears like a genuine warning, rather than an issue with the plug-in. Something/someone previously managed to set the heating threshold temperature of your thermostat to 4.5 degrees C, which is below the Nest minimum of 10 degrees C. Homebridge is doing its job alerting you to that inconsistency.

**Comment by leendersf** [comment]
O: thank you. My eco-temperature is set to off but my safety temperature is set to 4,5 celcius. Maybe that is why.
