### ISSUE TITLE
Nest Protect shows just one sensor: home occupied

### ISSUE THREAD

**Issue by David-Noble-at-work** [chrisjshull/homebridge-nest#385]
Prior to reinstalling 
- nodejs 14.16.0
- homebridge 1.3.3
- homebridge-nest 4.5.3

On Ubuntu 20.04.2 LTS all sensors were present. Now just the home occupied (HO) sensor shows up as a switch in the Home app. The Smoke and CO sensors are missing.

All sensors are listed as present on the Home Settings page. Only the Home Occupied sensor is represented in Room UI.

I would like to see and control all my sensors in the Room UI. Is there a way to do that? Did I mess up when I added the Nest accessory?

The Nest App shows and lets me control all sensors. I'll send logs if that would help. Let me know.

**Comment by adriancable** [comment]
@David-Noble-at-work - before we troubleshoot, what exactly are you expecting to see in the Home app? Sensor-only devices no longer show as tiles in the Home app in iOS 14 onwards. Just wanted to check first there's actually an issue to debug here.

**Comment by David-Noble-at-work** [comment]
Got it. Let me echo back what sounds like a HomeKit limitation for sensor accessories. 

The only thing I can do with Nest Protect in the Room UI is turn Home Occupancy On or Off. The sensors are noted as being present on the Home Settings panel. I can enable push notifications for "people present" there. I must go to the Nest App to--say--to do a sound checkup or silence an alarm (Smoke or CO) that goes off unexpectedly. No other functions are available. This is a HomeKit/Home App limitation.

I might like to see parity with the Nest App. Is it not possible to--say--provide sound checks in the Home Settings UI or silence an alarm from the Room UI or when an alarm goes off?

I suggest the Room UI for the latter because it might be quicker from there.

**Comment by adriancable** [comment]
@David-Noble-at-work - can you look in the Room (not the overview page) in the Home app and check that in the status trip at the top, you see '2 Alarm Sensors' or similar? If so, then everything is good.

Unfortunately, it's not possible to silence the alarm via the Nest API. On the Nest app, this is done by a Bluetooth LE broadcast from your phone, and it only works when you're within a few feet of the alarm. It's really a convenience feature so that if for example the alarm is mounted high up on the ceiling, you can stand underneath it with your phone to stop it instead of having to climb a ladder and press the physical button. It's not intended for 'remote' use when you're out of sight of the alarm. I believe (but will need to check) the same is true for the sound check-up function from the app. In this case it's not possible to replicate in HomeKit.

Regarding the 'Home Occupied' switch, just so you know, this is a property of your whole Nest account and not the Protects themselves. It represents (with the option to override) Nest's view of whether you're home or away. It uses information from all your devices to determine this, and isn't specific to any one device or device type.

**Comment by David-Noble-at-work** [comment]
Thanks for clearing these issues up for me. I verified that:

- The smoke and CO sensors show up at the top of the room they're in.
- The health and sound checks are performed by the Nest App using Bluetooth which requires proximity:(
- The Occupancy sensor also shows up in the room that the smoke and CO sensors reside. This, I expect is the occupancy sensor on the Nest Protect. I say that because I put the Occupancy switch in another room and it's there, not in the room with the Occupancy sensor.

Thanks for your support. Please close this issue unless you see work to do.

Have a good day.

Kind regards,
David Noble

**Comment by adriancable** [comment]
@David-Noble-at-work - this all sounds right. The Occupancy sensor is indeed that of the Nest Protect. (There is also the 'Home Occupied' switch which is a property of your Nest Home - this is what I thought you were referring to earlier - apologies if I got confused.) Closing now since I think we are in good shape.
