### ISSUE TITLE
Expose Light sensor in Thermostat / Protect as a Sensor

### ISSUE THREAD

**Issue by mofirouz** [chrisjshull/homebridge-nest#391]
Firstly, thank you so so much for this amazing project 🥇 

I'm controlling my Philips Lights via Homebridge whenever the Nest Protect Occupancy Sensor turns on/off - however in the summer, the room is quite lit and would like to avoid turning on the lights even if the occupancy sensor is on.

According to this link:
https://support.google.com/googlenest/answer/9330256?hl=en-GB

There is a light sensor in both Thermostat and Protect. Would it be possible to expose the light sensor of either/both Thermostat / Protect as a Sensor to Homebridge?

**Comment by adriancable** [comment]
@mofirouz - thanks for the suggestion! Unfortunately, as I far as I know, the light sensor isn't exposed via the API on either the Thermostat or the Protect. I am 95% certain (but not 100% since I have never actively looked for it) - I will leave this open and post an update if I find anything interesting.
