### ISSUE TITLE
Offline status not recognized

### ISSUE THREAD

**Issue by rda2** [chrisjshull/homebridge-nest#403]
The plugin currently does not recognize if the thermostat is offline, and continues to report the same temperature/status it had when it turned off.

The plugin should report to HomeKit when the thermostat is offline and show all sensors as offline as well

**Comment by adriancable** [comment]
@rda2 - we report the online/offline status to HomeKit as 'Status Active'. Unfortunately, since iOS 11 I think, HomeKit does not have a 'reachable' property or any other way to communicate online/offline status to the user.

**Comment by rda2** [comment]
Hey @adriancable, in that case, is it possible to stop responding to HomeKit so the thermostat goes into “no response” state? Other accessories seem to take that route when offline

**Comment by adriancable** [comment]
@rda2 - this plug-in is a bridge not a single accessory (because you might have multiple Nest products). It's possible for the whole bridge just to stop responding to requests, but this will make every accessory under the bridge show 'No Response'. Also, because HomeKit may not actually send requests for while, it isn't guaranteed that the 'No Response' state will show in a timely way.

There used be a way to do exactly what you want, which was an accessory's 'reachability' property. A bridge could set this on any accessory to false, and you would get an orange (!) symbol on the accessory. But, Apple removed this. The rationale was that HomeKit accessories should NEVER be unavailable, and Apple did not want to give device makers a 'way out' by providing the capability for devices to take themselves offline.

**Comment by rda2** [comment]
Completely makes sense. Perhaps if we discover that all Nest devices are offline, we report ‘No Response’ to HomeKit on the next update until at least one is responding?
