### ISSUE TITLE
Accessory Automation - HVAC State

### ISSUE THREAD

**Issue by xetra27** [chrisjshull/homebridge-nest#427]
The current "Accessory Automation" page lists "Eco Mode", "Fan" and "Home Occupied".
![Automation](https://user-images.githubusercontent.com/58535757/129495661-cf4e4f62-7938-4e26-be30-1b36cb6eb333.PNG)

Would it be possible to add "HVAC State" an perhaps the current temperature?

I am trying to automate a separate fan based on the running condition of the HVAC. It currently works fine based on the "Fan State", so adding a trigger for the HVAC state should work.

**Comment by adriancable** [comment]
@xetra27 - this request is outside the purview of the plug-in. Third-party HomeKit apps like Home+ allow creating automations based on the HVAC state and current temperature. If you use one of those instead of Apple's Home app to create your automation, you will be able to do what you are looking for.
