### ISSUE TITLE
iOS 12 Developer Beta

### ISSUE THREAD

**Issue by djfatal** [chrisjshull/homebridge-nest#43]
**Describe the bug**
Random Nest accessories are showing up as duplicates with no functionality and displaying "not supported".  The duplicate accessories also have a 'home' icon.

**To Reproduce**
1. Open HomeKit app

Include with your bug report this version info:
```sh
node --version
v7.10.0
homebridge --version
latest
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

**Comment by chrisjshull** [comment]
As this is the first iOS 12 beta, probably going to wait things out and see if iOS resolves it.

**Comment by leoneleone** [comment]
@djfatal 
Try removing the Nest Plugin entirely from Homebridge, running homebridge so that all Nest devices (including duplicates) are deleted from your HomeKit setup. Then add this nest plugin again. Make sure to stop homebridge processes entirely between removal of the plugin then re-running homebridge. Meaning don’t let homebridge run in the background while you make changes
