### ISSUE TITLE
'Heating Threshold Temperature' Set to Safety Temperature 4.5 Celsius Instead of Lower Threshold 10 Celsius in Eco Mode

### ISSUE THREAD

**Issue by RampageTiger** [chrisjshull/homebridge-nest#444]
**Describe The Bug:**
Plugin sets 'Heating Threshold Temperature' to safety temperature, 4.5 Celsius, instead of the lower heat threshold, 10 Celsius. This causes warning message in HomeBridge.

**To Reproduce:**
Turn on Nest in Eco mode
Set Eco Temperature to 10 C
Safety Temperature to 4.5 C.

**Expected behavior:**
Successfully sets set 'Heating Threshold Temperature' to 10 Celsius which is a valid temperature.

Include with your bug report this version info:
```sh
node --version
v14.17.4
homebridge --version
1.3.4
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`

```
[Nest] initing thermostat (P) "Master Bedroom Thermostat"
[Nest] Current temperature for Master Bedroom Thermostat is: 21.5 °C / 70.7 °F
[Nest] Current humidity for Master Bedroom Thermostat is: 49%
[Nest] Target temperature for Master Bedroom Thermostat is: 21.5 °C / 70.7 °F
[Nest] Cooling threshold temperature for Master Bedroom Thermostat is: 24.5 °C / 76.10000000000001 °F
[Master Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 4.5 exceeded minimum of 9
[Nest] Heating threshold temperature for Master Bedroom Thermostat is: 9 °C / 48.2 °F
[Nest] Online status for Master Bedroom Thermostat is: true
[Nest] Eco Mode for Master Bedroom Thermostat is: true
```

**Comment by adriancable** [comment]
@RampageTiger - I can't reproduce this. Can you give some more precise instructions? e.g. for "Turn on Nest in Eco mode" you need to tell us what "turn on" means. Heating mode? Cooling? Auto?

What does "safety temperature to 4.5 C" mean in your "steps to reproduce"? Are you trying to set the safety temperature to 4.5 C? Is it already set to 4.5 C before you start? (in which case, why is it at the end of your 'steps to reproduce'?)

Thanks.

**Comment by MeatAssassin** [comment]
I am getting a ton of similar errors when my thermostat is in eco mode while in heat or cool mode.  The error is This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.444444444444445 exceeded minimum of 10. See https://git.io/JtMGR for more info.

The error does not occur when the thermostat is not in eco mode.  Thanks for all of your hard work on the Nest plugin.

node --version
v14.17.6

homebridge --version
1.3.5

**Comment by adriancable** [comment]
This isn't an error - it's just a warning and you can safely ignore it.

It's a consequence of the fact that Nest applies different temperature band limits depending on the thermostat mode. (in Eco Mode, the lower band is the Safety Temperature limit, which is lower than the conventional setpoint limit of 9 degrees C). It isn't clear how to suppress this as with HomeKit you just set a single range limit for a single characteristic. I can't reduce that limit because that would then let you set temperatures below 9 degrees C in the Home app UI, which would then cause errors on the Nest side.

So, please just ignore it.

**Comment by tpitale** [comment]
https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings#this-plugin-generated-a-warning-from-the-characteristic

**Comment by adriancable** [comment]
As stated verbatim on that page:

`If the plugin is still functioning correctly, you can ignore these warnings.`

Please ignore these warnings. There is nothing I can do to remove them, as I explain above, due to the way Nest supports different temperature ranges under different circumstances (e.g. whether safety temps are active) and Homebridge thinks this is suspicious when it is not.

**Comment by tpitale** [comment]
Exactly, that's why I shared the link. So when others search for this message and find this issue it will also have a link to the home bridge explanation.
