### ISSUE TITLE
Utilize temperature and humidity sensors

### ISSUE THREAD

**Issue by DerDom** [chrisjshull/homebridge-nest#457]
The Nest Protect has temperature and humidity sensors:

https://support.google.com/googlenest/answer/9251133?hl=en

However, the data is not accessible through the official API but through OpenWeave. Since I would love to use my Nest Protect smoke detectors to get information about room temperature and humidity, would it be possible to add support?

https://opensource.google/projects/openweave
https://openweave.io
https://github.com/openweave/happy

**Comment by adriancable** [comment]
@DerDom - as per my earlier post this isn't (to my knowledge, or anyone else's) possible in software. If you want to do this, you can physically connect an Arduino to the internal sensors to read their values. There is nothing to suggest there is any other way, sorry.

The Nest Protect's network connectivity behaviour for the wired vs. battery models is well known. This plug-in already reports occupancy state (which is more or less motion detection) for wired protects.

**Comment by cybernard** [comment]
This may or may not be useful, but you can use Google takeout, and download the nest data.  By default google takeout has everything checked and you don't want that, uncheck everything but nest.  It will take eons longer to process your request if you don't and the download will be in the size range of many gigs instead of a few kb.
