### ISSUE TITLE
Current auth method config can lead to unexpected results and auth failures

### ISSUE THREAD

**Issue by CharlieHawker** [chrisjshull/homebridge-nest#459]
**Is your feature request related to a problem? Please describe.**
I recently had cause to re-connect my Nest login; I was using cookie-based Google auth before but this time I chose the refreshToken method. Upon restarting Homebridge I found repeated console errors regarding having signed out of Google; which I thought was related to the refreshToken config I had set up.

It took me too long to realise that in actual fact the google cooke-auth config was still in situ in the collapsed config options in the homebridge UI, and once I removed them it worked perfectly as expected using the refreshToken that was already in place.

**Describe the solution you'd like**
If you populate an auth method it should remove any pre-populated auth methods at point of save, or at least remind you to clear any other values, since it won't be obvious via the UI when those accordions are collapsed.

**Describe alternatives you've considered**
I had a brief look at the plugin docs for homebridge to see if there was a validator that might work for this, but wasn't sure I could see one - you may be able to fathom a validator to do it.

Alternatively I would suggest that the auth method should be a dropdown option that is part of the configuration, so that the plugin pics the correct credentials based on the chosen auth method.

**Comment by adriancable** [comment]
Hi @CharlieHawker - thanks for reaching out and sorry this 'glitch' caused you trouble!

The Homebridge config UI part of the plug-in was put together by another couple of developers (@athal7 and @donavanbecker) as I'm not super familiar with how that all works.

But, I can certainly change the plug-in so that if you have both cookies and refreshToken in the config.json, it exits with an error saying "you can't have both", at least so you can then go back into the config and remove the cookies. Do you think this change would have made things clearer in your case?

**Comment by donavanbecker** [comment]
@adriancable Yeah I don't think config.schema.json would be able to remove one field if another field is already filled in. A log that stops the load of the plugin if both are filled would be the best route.

**Comment by adriancable** [comment]
@CharlieHawker + @donavanbecker: this is "fixed" in 4.6.3 (the plug-in now stops if both are filled in).
