### ISSUE TITLE
Silence Nest Protect

### ISSUE THREAD

**Issue by fishbotics** [chrisjshull/homebridge-nest#478]
**Is your feature request related to a problem? Please describe.**
I'm often cooking when my smoke alarm goes off. It's frustrating to have to wash my hands, reach into my pocket, unlock my  phone and turn it off.

**Describe the solution you'd like**
It would be great if I could silence the smoke alarm via Siri so I don't have to grab my phone and hit the silence button manually.

**Comment by adriancable** [comment]
@fishbotics - the silence function you find in the Nest app works via BLE, and unfortunately the protocol for it is not known. It is probably possible to reverse-engineer, but to my knowledge it hasn't been done.

My suggestion - you keep a long, firm stick (like a broom handle) near your stove in the kitchen. Then if the smoke alarm goes off, rather than using your phone at all you can quickly use the stick to press the button on the Nest Protect.

This is what I do - it is much more convenient than any electronic means of silencing (like using an app).
