### ISSUE TITLE
Link Account/Login Screen Blank

### ISSUE THREAD

**Issue by chaselampley** [chrisjshull/homebridge-nest#488]
When I click the Link Account button I see the example of the one-time access code but when I click login the screen is blank. 
![Nest](https://user-images.githubusercontent.com/22333523/148009047-c7f69cc0-9730-44a2-8d38-aa00c42627e6.JPG)

**Comment by adriancable** [comment]
@chaselampley - please don't post duplicate issues, especially issues that I've taken time to pin so you can't possibly miss them.

It means that instead of spending time working on the plug-in, I am spending time writing the same responses over and over again to different people. I hope you understand that this helps no-one.
