### ISSUE TITLE
Implement some sort of debounce?

### ISSUE THREAD

**Issue by zllovesuki** [chrisjshull/homebridge-nest#5]
Say if I'm too uncertain about what temperature I want and dragged the slider too many times, it might hit the Firebase's (undocumented) throttling. Possible to do some debounce in that regards?

btw Awesome fork! <3

**Comment by chrisjshull** [comment]
Hi @zllovesuki, the temperature setting functions should already be debounced with a 5 second delay: https://github.com/chrisjshull/homebridge-nest/blob/baa50fa41769f33286c763d4d47342c918fadf6e/lib/nest-thermostat-accessory.js#L322
(Credit to Ignacio Bona Piedrabuena)

Are you finding you frequently hit the rate limit? I've only ever hit it while testing this project, but I'd love to brainstorm improvements with you.

**Comment by zllovesuki** [comment]
@chrisjshull oh lmao I need to RTFS (Read the Fking Source) before opening an issue.

But I did hit a bug before your #4 PR where nothing would work after the limit was reached. There wasn't an error saying "FIREBASE ERROR", the whole home bridge would just freeze. I need to see if I can replicate that.

**Comment by zllovesuki** [comment]
Although,

```
Feb 12 22:35:59 homebridge homebridge[1217]: [2018-2-12 22:35:59] [Nest] Trying to set temperature 18
Feb 12 22:36:01 homebridge homebridge[1217]: [2018-2-12 22:36:01] [Nest] Trying to set temperature 19
```

They are probably not debounced?...

**Comment by chrisjshull** [comment]
Hmm, looks like that log is outside of the debounce: https://github.com/chrisjshull/homebridge-nest/blob/baa50fa41769f33286c763d4d47342c918fadf6e/lib/nest-thermostat-accessory.js#L297

So that log will happen for each event from HomeKit. The actual "data sent" log is "Temperature set to ...".

I can certainly see how that would be confusing. (Though I do like that each has it's own log they could probably be clearer.) 

Do you want to open a PR for that?

**Comment by zllovesuki** [comment]
Interesting. If that's a harmless log message, I don't think there's a problem with the implementation. Thank you for answer my question though. 🖖
