### ISSUE TITLE
Nest Thermostat offline in Nest app on iOS

### ISSUE THREAD

**Issue by pkajaba** [chrisjshull/homebridge-nest#504]
Hello,

thanks a lot for an amazing plugin!

I have started using homebridge-nest recently and I have noticed that thermostat is offline in the app.

**Model I have:** Nest Learning Thermostat 3rd gen

Is this expected or I might have configured something wrong?

Thanks!

**Comment by adriancable** [comment]
@pkajaba - what do you mean when you say the "thermostat is offline in the app". Which app are you referring to?

**Comment by pkajaba** [comment]
> @pkajaba - what do you mean when you say the "thermostat is offline in the app". Which app are you referring to?

Hello @adriancable. Apologies for not clarifying this more clearly.

I am referring to the official app by Google https://apps.apple.com/gb/app/nest/id464988855

![image](https://user-images.githubusercontent.com/15980400/152050602-d5301cbe-36fb-4569-85de-17d1758f74a3.png)

**Comment by adriancable** [comment]
@pkajaba - that's very interesting. It's hard to see how the plug-in could be responsible for the thermostat really going offline ... can you share why you think the two are related? For example, does the thermostat consistently go offline when you do a specific operation in HomeKit with the thermostat?

Any additional information you have would be very helpful! Thank you.

**Comment by pkajaba** [comment]
> @pkajaba - that's very interesting. It's hard to see how the plug-in could be responsible for the thermostat really going offline ... can you share why you think the two are related? For example, does the thermostat consistently go offline when you do a specific operation in HomeKit with the thermostat?

It is flipping offline/online, but I haven't figured out the pattern of the behaviour yet. It is worth noting that it is stable in HomeKit/HomeBridge.

> Any additional information you have would be very helpful! Thank you.

What kind of information could be useful?

- I am using cookie auth through Google Account currently. 
- HomeBridge is running on Ubuntu 20.04 server
- I am running latest version of the HomeBridge and homebridge-nest.

**Comment by adriancable** [comment]
@pkajaba - HomeKit does not really have an concept of an "offline" device state, so it is likely (unless you are seeing a purely Nest app glitch) that when it says "offline" in the Nest app, the thermostat really is offline and won't respond to your HomeKit commands (at least until it goes back online).

When the plug-in is running, unless you do something on the HomeKit side it isn't sending any commands to the Nest service, so if the thermostat is flipping offline/online when you are doing nothing in HomeKit then I would be surprised if this issue is due to the plug-in. So it would be helpful (in terms of 'additional information') if you can pin down which specific kinds of actions on the HomeKit side do indeed result in the thermostat going "offline". Thank you!

**Comment by adriancable** [comment]
Closing as no further response from @pkajaba so impossible to debug further.

**Comment by pkajaba** [comment]
Thanks a lot. I think that it could have been some rate limiting on Google side since it did not happen afterwards.

**Comment by adriancable** [comment]
@pkajaba - great, please reach out if it happens again and we'll dig deeper together.
