### ISSUE TITLE
Nest Protect Smoke Detectors "No Response" in HomeKit

### ISSUE THREAD

**Issue by johnlietzke** [chrisjshull/homebridge-nest#541]
The Nest Protect Smoke Detectors are "No Response" in HomeKit.  This includes Occupancy Sensor, Smoke and CO2.

**Comment by adriancable** [comment]
'No Response' in HomeKit means your endpoint device (e.g. your iPhone, where you're running the Apple Home app) can't reach the machine running Homebridge, or can't see it over mDNS.

It is almost always due to a network configuration mistake, e.g.

- you're using a mesh network and have wired devices connected to the wrong place (e.g. to the satellites)
- you're not using a mesh network and have wired devices connected to the wrong place (e.g. to the modem, not the router)
- your router is blocking multicast DNS traffic between interfaces (look for settings called 'iGMP proxy', 'multicast filtering' etc.)

I recommend you do some Googling as the Internet is full of advice on how to set up a stable HomeKit set-up and what can go wrong to cause 'No Response' issues. This isn't a plug-in issue. Hope this helps.
