### ISSUE TITLE
two houses with nests - both showing up in homekit

### ISSUE THREAD

**Issue by montanaishome** [chrisjshull/homebridge-nest#56]
So, I have a Nest thermostat at my house.  My parents also have a Nest thermostat at their house, and they have added me as a user on their thermostat.  So, both locations are tied to my nest ID.

So, now my parents house (or at least their thermostats) are showing up as an unnamed room in home.app!  I don't want to adjust their thermostat when I come or go from my house.  Is there any way to remove this, or to show it as a separate "house"?

**Comment by mmasnjak** [comment]
You can filter by `structureId` to cut your parents' devices out.

**Comment by chrisjshull** [comment]
@montanaishome, let me know if `structureId` isn't what you're looking for, okay?

**Comment by ntableman** [comment]
Just curious if anyone else has been able to get structureId to work? I have put in the id's as listed in the log and tried removing the - and they are still not filtering out the unwanted devices.

**Comment by adriancable** [comment]
Can you kindly post your config.json (after redacting the account email and password of course) and also the console output when running homebridge?

Thanks!

**Comment by dew1803** [comment]
Are you using the device structureId? I messed with this for a good while,
admittedly because I didn't really know what I was doing. In the nest app,
you have to create a second Structure, for example I have Cameras and
Thermostats, and then in my config.json reference structureId of the
cameras structure to filter all the cameras out.

**Comment by markob100** [comment]
Working for me. Make sure you have “StructureId” not “StructureID” in config.json. I did at first and couldn’t work out what was wrong since it just failed silently. 

Also what do you mean by ‘IDs’ - presumably you’re just putting one structure ID? Just to check you’re not using a string of device IDs instead.
