### ISSUE TITLE
Nest Secure status

### ISSUE THREAD

**Issue by jayewyo** [chrisjshull/homebridge-nest#59]
**Is your feature request related to a problem? Please describe.**
Nest API now allows read access of the Nest Secure security status. Would love to see this integrated into homebridge.

**Describe the solution you'd like**
Integration into homebridge

**Describe alternatives you've considered**
NA

**Additional context**
Currently, the security status shows "device skipped"

**Comment by sghamaty** [comment]
Is Nest Secure not supported? Im having problems setting it up and thought it was a user error. I get the error in the Home app "Additional Set up Required. Add related accessories with "Homebridge" in the manufacturer's app.

@jayewyo  where do you see "Device skipped"?

**Comment by leoneleone** [comment]
@jayewyo 
I don’t think Nest Secure is supported by this plugin yet. 

I don’t have Nest Secure. Can I ask, how is Nest Home/Away tied into Nest Secure?

**Comment by jayewyo** [comment]
Right, I think it would be a good feature to add as the Nest API now exposes the security status. @leoneleone The Nest Secure sets the Home/Away status when you arm and disarm the security. From the app, if you set to away, it automatically sets security.

**Comment by leoneleone** [comment]
@jayewyo 
The published Nest api regarding Nest Secure is very limited. It only allows reading of the Nest Security State, which I believe isn’t compatible with HomeKit (and currently not very useful).

**Comment by sghamaty** [comment]
Im a little new to the guts of the Nest API and Nest system.

I have a Nest Hello and a Nest Secure. Both don't show up as accessories using homebridge-nest. After adding homebridge to Home, screen shows "Identify Accessory" 1 of 2. When clicking next, a message that says "Additional Set up Required, Add related accessories with "Homebridge" in the manufacturer's app." Neither shows up.

As a end user, it would be nice to set Nest Hello and Nest Secure to home/away. As a end user it looks like the system sets home/away in the app, not individual nest products. If we have to set each product individually to home/away and api doesnt support it then were stuck till the support comes. 
 @leoneleone Is that true, we'd have to wait for Nest support to get these two products to work?

**Comment by leoneleone** [comment]
@sghamaty 
You should see a motion Sensor populate in the Home.app for your Nest Hello. If you use Eve.app you will also see an AWAY switch which can be toggled. 
Previously, in the Nest.app, you were able to nominate an individual Nest Cam to “decide if you’re away”. Toggling the AWAY switch in HomeKit would then set the Nest Away/Home status correctly (According to Away behaviour set within the Nest.app.
This no longer works reliably anymore, and my nominated “decide if you’re away” camera is no longer selectable within the Nest.app for this particular function, only my Phone’s location and my Nest Protects are eligible to “Decide if I’m Away”.

@chrisjshull 
I think there should be one single AWAY accessory exposed to HomeKit for the entire Nest Home structure, rather than an Away toggle for each camera device.

https://github.com/chrisjshull/homebridge-nest/issues/64
